### ISSUE TITLE
没有pages文件夹 ，build出错

### ISSUE THREAD

**Issue by sakurayun** [Akegarasu/vup-song-list#1]
```
npm run build

> vup-song-list@1.0.0 build
> next build


> Build error occurred
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (C:\Users\yun_er\Downloads\vup-song-list-main\node_modules\next\dist\lib\find-pages-dir.js:33:11)
    at C:\Users\yun_er\Downloads\vup-song-list-main\node_modules\next\dist\build\index.js:116:45
    at async Span.traceAsyncFn (C:\Users\yun_er\Downloads\vup-song-list-main\node_modules\next\dist\trace\trace.js:75:20)
    at async Object.build [as default] (C:\Users\yun_er\Downloads\vup-song-list-main\node_modules\next\dist\build\index.js:82:25)
```
创建 `pages` 文件夹后 `build` 出错
```
npm run build

> vup-song-list@1.0.0 build
> next build

info  - Checking validity of types

Failed to compile.

./components/SongDetail.component.jsx
35:11  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
45:11  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/SongListFilter.component.jsx
78:17  Error: Missing "key" prop for element in iterator  react/jsx-key

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules

```

**Comment by Akegarasu** [comment]
还没改完...别急别急

**Comment by sakurayun** [comment]
> 还没改完...别急别急

好捏~
建议用daisyui捏（
https://daisyui.com/

**Comment by Akegarasu** [comment]
没必要引入新的 ui 框架，会变得更复杂

**Comment by sakurayun** [comment]
> 没必要引入新的 ui 框架，会变得更复杂

加油捏
