### ISSUE TITLE
不好意思 又来打扰了 

### ISSUE THREAD

**Issue by omanikk** [Akegarasu/vup-song-list#2]
我输入scripts/example.xlsx 并且运行 converter.py 后并未生成 music_list.json
报错如下
PS D:\Users\Desktop\vup-song-list-main\vup-song-list-main\scripts> python converter.py
Traceback (most recent call last):
  File "D:\Users\Desktop\vup-song-list-main\vup-song-list-main\scripts\converter.py", line 4, in <module>
    song_df = pd.read_excel('./muisc.xlsx')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1376, in __init__
    ext = inspect_excel_format(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1250, in inspect_excel_format
    with get_handle(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\common.py", line 798, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: './muisc.xlsx'

您看方便加您个联系方式吗 给您发电赞助一下 毕竟这么麻烦你

**Comment by omanikk** [comment]
歌单我已生成 xlsx文件按代码改名就好了  但是我又遇到新的问题
./components/SongListFilter.component.jsx:5:0
Module not found: Can't resolve '../config/constants'
  3 | 
  4 | import MandarinBtn from "../components/MandarinBtn.component";
> 5 | import { config } from "../config/constants";
  6 | 
  7 | const languageCategories = config.LanguageCategories;
  8 | const remarkCategories = config.RemarkCategories;

Import trace for requested module:
./pages/index.js

https://nextjs.org/docs/messages/module-not-found
是配置文件没有填写必写项吗  
期待添加您的联系方式  
麻烦这么久给您冲个电

**Comment by omanikk** [comment]
给constants.js文件改名后已成功进入网页 但是报错如下 我继续研究下
Server Error
ModuleParseError: Module parse failed: Unexpected token N in JSON at position 120 while parsing near '...\u884c", "remarks": NaN, "initial": "A",...'
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
SyntaxError: Unexpected token N in JSON at position 120 while parsing near '...\u884c", "remarks": NaN, "initial": "A",...'
    at JSON.parse (<anonymous>)
    at parseJson (D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:15303:17)
    at JsonParser.parse (D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:95552:7)
    at D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:49543:26
    at processResult (D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:49256:11)
    at D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:49316:5
    at D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:139505:3
    at iterateNormalLoaders (D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:139331:10)
    at D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:139322:4
    at D:\Users\Desktop\vup-song-list-main\vup-song-list-main\node_modules\next\dist\compiled\webpack\bundle5.js:49290:15

This error happened while generating the page. Any console logs will be displayed in the terminal window.

**Comment by omanikk** [comment]
已成功进入网页 报错如下  我继续研究下。。。
./public/music_list.json
Module parse failed: Unexpected token N in JSON at position 120 while parsing near '...\u884c", "remarks": NaN, "initial": "A",...'
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
SyntaxError: Unexpected token N in JSON at position 120 while parsing near '...\u884c", "remarks": NaN, "initial": "A",...'
    at JSON.parse (<anonymous>)

**Comment by omanikk** [comment]
跑起来了！！！！！！感谢！！！！请问一下网页底图 头像之类的配置项  都是在config文件夹吗

**Comment by Akegarasu** [comment]
不是的 底图等图片请直接替换 `public/assets` 文件夹内的图片 其余的配置项都在config内，直接修改就可以了

我的爱发电 [https://afdian.net/@akibanzu](https://afdian.net/@akibanzu)

没考虑到普通用户部署的问题，有时间的话我会补充一下文档的

**Comment by Akegarasu** [comment]
补充了一下文档，可以参考一下，希望有帮助

**Comment by Akegarasu** [comment]
哦对记得更新一下项目文件（如果使用git可以直接用`git pull`， 如果是网页下载的压缩包的话重新下载一下`pages/index.js`替换一下（？
上个月的时候修复了一个无法预览视频的bug但是没有上传

**Comment by omanikk** [comment]
嗯嗯好的！！这就更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月15日(星期一) 晚上10:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Akegarasu/vup-song-list] 不好意思 又来打扰了  (Issue #2)





 
哦对记得更新一下项目文件（如果使用git可以直接用git pull， 如果是网页下载的压缩包的话重新下载一下pages/index.js替换一下（？
 上个月的时候修复了一个无法预览视频的bug但是没有上传

**Comment by omanikk** [comment]
嗯嗯！！！已发电！感谢您的开发




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月15日(星期一) 晚上10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Akegarasu/vup-song-list] 不好意思 又来打扰了  (Issue #2)





 
补充了一下文档，可以参考一下，希望有帮助
